#include <stdio.h>
#include "../include/libtcod.hpp"
class Actor;
#include "destructible.hpp"
#include "attacker.hpp"
#include "ai.hpp"
#include "pickable.hpp"
#include "container.hpp"
#include "gui.hpp"
#include "actor.hpp"
#include "map.hpp"
#include "engine.hpp"