#include <stdio.h>
#include <algorithm>
#include <math.h>
#include "../include/libtcod.hpp"
#include "../include/cereal/cereal.hpp"
class Actor;
#include "effects.hpp"
#include "destructible.hpp"
#include "attacker.hpp"
#include "ai.hpp"
#include "pickable.hpp"
#include "container.hpp"
#include "gui.hpp"
#include "actor.hpp"
#include "map.hpp"
#include "engine.hpp"